server:
  port: 8002

spring:
  application:
    name: crash2cost-api

  mongodb:
    uri: mongodb://localhost:27017/crash2cost

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${env.JWT_SECRET}
  expiration: ${env.JWT_EXPIRATION:3600000}

upload:
  directory: uploads

cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    '[io.github.mrlevi1112]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.web]': INFO
